### ISSUE TITLE
请问要如何配置vite.config.js里的preprocessorOptions呢？

### ISSUE THREAD

**Issue by bojun1995** [keyding/vite-crx-vue#1]
这样似乎会插入多次，我去rollup-plugin-chrome-extension没有找到相应配置，请问可以启发一下吗？

```
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: ['@import "./src/style/base/globalVariable.scss";'],
      },
    },
  },

```

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/27986257/170053866-140b5502-2ce6-4ba0-9951-7a96379548f4.png">

**Comment by bojun1995** [comment]
不好意思，additionalData的格式搞错了😂

**Comment by keyding** [comment]
来晚了，解决就好。😁
