### ISSUE TITLE
What about i18n?

### ISSUE THREAD

**Issue by yang-he** [keyding/vite-crx-vue#2]
Awesome template! Thanks for the great work!

I wonder if you plan to support i18N?  At the moment when creating a `_locales` dir in my `src` dir it seems that it's not published to the `dist`.

https://developer.chrome.com/docs/extensions/reference/i18n/

**Comment by keyding** [comment]
It would be a great pleasure to help you.

![image](https://user-images.githubusercontent.com/20431351/184317451-e28a0481-01d0-42e1-a4f9-e72aa808c045.png)

`manifest.json`
```json
{
    "default_locale": "en",
    "description": "__MSG_extDescription__",
}
```
You should put it in the `public` directory. 

after build

![image](https://user-images.githubusercontent.com/20431351/184318156-4c1b3c80-0b40-4e7b-b3f3-cd7cd495a051.png)

I'll update and commit later.

**Comment by yang-he** [comment]
Worked like a charm, thank you!

Closing this issue now.
